### ISSUE TITLE
Y no puede ser con constraintLayout y que solo tenga una jerarquia de vista?

### ISSUE THREAD

**Issue by manelcc** [Albrodiaz/Travelling#2]
https://github.com/Choketido/Travelling/blob/8c9770be40e4791f90e6ad78fd092a63b69f4c18/app/src/main/res/layout/onboarding_layout.xml#L2

Fijate que una pantalla tan sencilla ya has tenido que generar 1 contenedor padre y 2 contenedores hijos.
Con ConstraintLayout con solo el contenedor padre ya podrías tenerlo resuelto.

**Comment by Albrodiaz** [comment]
Buenas noches Manel. Lo tenia en cuenta, pero al ver las prácticas siguientes me fijé que es obligatorio usar constraintslayout, entonces decidí usar linear para practicar otro tipo de construcción.
Las siguientes ya irán en constraintlayout.

**Comment by manelcc** [comment]
Fantástico
