### ISSUE TITLE
Poner modificadores en los Fields de java o Properties en Kotlin

### ISSUE THREAD

**Issue by manelcc** [Albrodiaz/Travelling#5]
https://github.com/Choketido/Travelling/blob/4a59f5825d12f33bcab8edc1096f1541c759892b/app/src/main/java/es/travelworld/travelling/view/HomeActivity.java#L22-L24
Debes indicar el modificador private, protected o public en los fields de las clases.
Por cierto sino se pone ningún modificador que tipo de modificador es??

**Comment by Albrodiaz** [comment]
Buenas tardes!
Se me pasó poner el modificador private en esos atributos, los he añadido a
la última rama que tengo, la del recyclerview.
Si no recuerdo mal, al no poner modificador se aplica default, ¿no?
A veces me lío con Kotlin, que al no poner nada es público. Ahora mismo lo
modifico!

Aprovecho para hacerle una pregunta acerca de Git. Cada actividad la estoy
haciendo en una rama distinta, una vez finalizado todos los ejercicios,
¿debería de hacer un merge en la rama en la que quiera fusionar todo?

Gracias, Manel!
